version: '3'

services:
  db:
    build: ./BDD-GIS
    image: duunky/dunkyandfilscorporation:BDD-GIS
    container_name: BDD-GIS
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: dunkyandfilscorporation
      MYSQL_ROOT_PASSWORD: root
    networks:
      my_network:
        ipv4_address: 172.16.238.10

  web:
    build: ./server-web-GIS
    image: duunky/dunkyandfilscorporation:server-web-GIS
    container_name: server-web-GIS
    ports:
      - "8080:80" 
    networks:
      my_network:
        ipv4_address: 172.16.238.11

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
