version: '3'

services:
  db:
    build: ./BDD-GIS
    image: duunky/dunkyandfilscorporation:BDD-GIS
    container_name: BDD-GIS
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: dunkyandfilscorporation
      MYSQL_ROOT_PASSWORD: root
    networks:
      my_network:
        ipv4_address: 172.16.238.10

  web:
    build: ./server-web-GIS
    image: duunky/dunkyandfilscorporation:server-web-GIS
    container_name: server-web-GIS
    ports:
      - "8080:8080" 
      - "9000:80"
    networks:
      my_network:
        ipv4_address: 172.16.238.11

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:8080"
    networks:
      my_network:
        ipv4_address: 172.16.238.12
        
  adminer:
    image: adminer
    ports:
      - "8001:8080"
    networks:
      my_network:
        ipv4_address: 172.16.238.13
        
networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
